apiVersion: v1
kind: Service
metadata:
  name: {{ include "nablagames.fullname" . }}-jump
  labels:
    app: jump
  {{- include "nablagames.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jump.type }}
  selector:
    app: jump
  {{- include "nablagames.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.jump.ports | toYaml | nindent 2 -}}