apiVersion: v1
kind: Service
metadata:
  name: {{ include "nablagames.fullname" . }}-leaderboard
  labels:
    app: leaderboard
  {{- include "nablagames.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: leaderboard
  {{- include "nablagames.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30002