apiVersion: v1
kind: Service
metadata:
  name: {{ include "nablagames.fullname" . }}-lobby
  labels:
    app: lobby
  {{- include "nablagames.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lobby.type }}
  selector:
    app: lobby
  {{- include "nablagames.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.lobby.ports | toYaml | nindent 2 -}}