apiVersion: v1
kind: Service
metadata:
  name: {{ include "nablagames.fullname" . }}-punch
  labels:
    app: punch
  {{- include "nablagames.labels" . | nindent 4 }}
spec:
  type: {{ .Values.punch.type }}
  selector:
    app: punch
  {{- include "nablagames.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.punch.ports | toYaml | nindent 2 -}}