apiVersion: v1
kind: Service
metadata:
  name: {{ include "nablagames.fullname" . }}-surreal
  labels:
    app: surreal
  {{- include "nablagames.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: surreal
  {{- include "nablagames.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000