apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump
  labels:
    app: jump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jump
  template:
    metadata:
      labels:
        app: jump
    spec:
      containers:
      - name: jump
        image: hugo4715/nablajump:latest
        ports:
        - containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: jump
  labels:
    app: jump
spec:
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: jump