apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
  labels:
    app: lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      containers:
      - name: lobby
        image: hugo4715/nablalobby:latest
        ports:
        - containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: lobby
  labels:
    app: lobby
spec:
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: lobby
  