jump:
  jump:
    image:
      repository: hugo4715/nablajump
      tag: latest
  ports:
  - port: 25565
    targetPort: 25565
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
lobby:
  lobby:
    image:
      repository: hugo4715/nablalobby
      tag: latest
  ports:
  - port: 25565
    targetPort: 25565
  replicas: 1
  type: ClusterIP
proxy:
  slots: 20
  ports:
  - nodePort: 30000
    port: 25565
    targetPort: 25577
  proxy:
    image:
      repository: hugo4715/nablaproxy
      tag: latest
  replicas: 1
  type: NodePort
punch:
  ports:
  - port: 25565
    targetPort: 25565
  punch:
    image:
      repository: hugo4715/nablapunch
      tag: latest
  replicas: 1
  type: ClusterIP
